### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"divya@gmail.com",
    "password":"12345678"
}


### Find a particular user with id 1
GET http://localhost:3000/auth/1


### Find all users with a given email
GET http://localhost:3000/auth?email=divya@gmail.com

### Delete a particular user with id 1
DELETE  http://localhost:3000/auth/1