#########################################
### SignUp
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"divya2@gmail.com",
    "password":"12345678"
}

#########################################
### SignIn
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"divya2@gmail.com",
    "password":"12345678"
}


### Find a particular user with id 1
GET http://localhost:3000/auth/2


### Find all users with a given email
GET http://localhost:3000/auth?email=divya1@gmail.com

### Delete a particular user with id 1
DELETE  http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "id":1,
    "email":"utsav@gmail.com",
    "password":"12345678"
}
